weights: ./yolov5l.pt
cfg: ./models/yolov5l.yaml
data: E:/current work/newfl/yolov5/dataset/data.yaml
hyp: data/hyp.scratch.yaml
epochs: 100
batch_size: 2
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 1
project: runs/train
entity: null
name: finalModel
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs\train\finalModel
total_batch_size: 2
